stages:
  - build
  - test
  - deploy
build:
  stage: build
  script:
<<<<<<< HEAD
    - bash .gitlab-pull.sh
test:
  stage: test
  script:
    - echo "ok"
deploy:
  stage: deploy
  script:
    - bash .gitlab-deploy.sh
  when: manual
  only:
   - master
=======
    - echo "ok"
    - bash .gitlab-deploy.sh
>>>>>>> staging
