stages:
  - build
  - test
  - deploy
build:
  stage: build
  script:
    - bash .gitlab-pull.sh
test:
  stage: test
  script:
    - echo "ok-feature"
deploy:

  stage: deploy
  script:
    - bash .gitlab-deploy.sh
  when: manual
  only:
   - master
